version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.response
    image: response
    container_name: response
    entrypoint: bash
    command: /app/startup.sh
    ports:
      - "8181:8181"
    # depends_on:
    #   - db
    # environment:
    #   POSTGRES: "true"
    env_file: .env
    volumes:
      - ./:/app
      - ../:/response
      - pypd:/app/pypd
    stdin_open: true
    tty: true

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

  # db:
  #   image: "postgres:12.3"
  #   container_name: postgres_repsonse
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB=response_docker
  #     - POSTGRES_USER=VtIGfiLGOCLayxRWFVWMkRPYRCwgRcfj
  #     - POSTGRES_PASSWORD=aBrplYbd86dJ8DYJ7yxR3lMkNettFPisrrPVcopRbwfayJ80DIqorI4DfRmd1k3C
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/

  # ngrok:
  #   image: gtriggiano/ngrok-tunnel
  #   container_name: ngrok
  #   environment:
  #     TARGET_HOST: "response"
  #     TARGET_PORT: 8181
  #   ports:
  #     - "4040:4040"
  #   depends_on:
  #     - response

volumes:
  postgres_data:
  pypd:
